spring:
  application:
    name: url-shortener

  datasource:
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:46487/railway?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: JOhqNxVDpfIHEwghRtugiFqDnpQjVxme
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  data:
    redis:
      host: notable-louse-102015.upstash.io
      port: 6379
      username: default
      password: gQAAAAAAAY5_AAIocDExOGVhNzhkYWVjNmE0YWQzODQ1YjBiMWI4MzdjYTk1OHAxMTAyMDE1
      ssl:
        enabled: true


server:
  port: 8080

app:
  base-url: http://localhost:8080
  short-code-length: 7
  cache-ttl-hours: 24

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always